[package]
name = "sample"
version = "0.1.0"
authors = ["imkgerC <imrund08@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
[lib]
name="core"
path="src/lib.rs"
[[bin]]
name="testing"
path="src/main.rs"
